services:
  app:
    container_name: app
    build:
      context: app
      target: builder
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT
    ports:
      - 8000:8000
    depends_on:
      - pg
      - api

  api:
    container_name: api
    build:
      context: api
      target: builder
    stop_signal: SIGINT
    ports:
      - 8001:8000
    depends_on:
      - pg

  pg:
    container_name: pg
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./db/.env
    volumes:
      - vol_pg:/var/lib/postgresql/
    restart: always

volumes:
  vol_pg:
