version: "3"

services:
  app:
    container_name: app
    build: ./app
    ports:
      - 8000:8000
    env_file:
      - ./app/.env
    volumes:
      - ./app:/home/app
    depends_on:
      - api
      - pg

  api:
    container_name: api
    build: ./api
    ports:
      - 8001:5000
    env_file:
      - ./api/.env
    volumes:
      - ./api:/home/app
    depends_on:
      - pg

  pg:
    container_name: pg
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./db/.env
    volumes:
      - vol_pg:/var/lib/postgresql/
    restart: always

volumes:
  vol_pg:
