
###

http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/docs?tag=app:config
Accept: application/json

###

GET http://127.0.0.1:8000/docs/23
Accept: application/json

###

DELETE http://127.0.0.1:8000/docs
Accept: application/json
Content-Type: application/json

{
  "id": 9
}

###

POST http://127.0.0.1:8000/docs
Accept: application/json
Content-Type: application/json

{
  "tag": "app:config",
  "data": "{\"admin:email\": \"admin@nikolav.rs\"}"
}

###

