
###
http://127.0.0.1:5000/
Accept: application/json

###
http://127.0.0.1:5000/admin_email
Accept: application/json

###

POST http://127.0.0.1:5000/sum2nums
Accept: application/json
Content-Type: application/json

{
  "x1": 1, 
  "x2": 22
}
###
