

###
http://127.0.0.1:8000/
Accept: application/json

###
GET http://127.0.0.1:8000/docs?tag=@2
Accept: application/json

###

DELETE http://127.0.0.1:8000/docs
Accept: application/json
Content-Type: application/json

{
  "id": 3
}

###

POST http://127.0.0.1:8000/docs
Accept: application/json
Content-Type: application/json

{
  "tag": "@2",
  "data": "{\"admin:email\": \"admin@nikolav.rs\"}",
  "id": 7
}

###

